import type { Lead, Activity, Alert, Course, Matriculation, Grade, AppSettings } from "./types"

export const mockCourses: Course[] = [
  {
    id: "1",
    name: "Análise e Desenvolvimento de Sistemas",
    level: "graduacao",
    format: "hibrido",
    duration: "2.5 anos",
    price: 18000,
    startDate: new Date("2024-03-01"),
    enrollmentDeadline: new Date("2024-02-15"),
  },
  {
    id: "2",
    name: "MBA em Gestão de Projetos",
    level: "pos",
    format: "online",
    duration: "1.5 anos",
    price: 24000,
    startDate: new Date("2024-04-10"),
    enrollmentDeadline: new Date("2024-03-25"),
  },
  {
    id: "3",
    name: "Técnico em Enfermagem",
    level: "tecnico",
    format: "presencial",
    duration: "2 anos",
    price: 12000,
    startDate: new Date("2024-02-15"),
    enrollmentDeadline: new Date("2024-01-30"),
  },
  {
    id: "4",
    name: "Especialização em Marketing Digital",
    level: "especializacao",
    format: "online",
    duration: "8 meses",
    price: 8500,
    startDate: new Date("2024-03-05"),
    enrollmentDeadline: new Date("2024-02-20"),
  },
  {
    id: "5",
    name: "Excel Avançado e VBA",
    level: "profissionalizante",
    format: "online",
    duration: "3 meses",
    price: 1200,
    startDate: new Date("2024-02-01"),
    enrollmentDeadline: new Date("2024-01-25"),
  },
]

export const mockLeads: Lead[] = [
  {
    id: "1",
    name: "Maria Silva",
    email: "maria.silva@email.com",
    phone: "(11) 99999-9999",
    status: "interessado",
    lastContact: new Date("2024-01-15"),
    nextContact: new Date("2024-02-01"),
    educationalBackground: "Ensino Médio Completo",
    interestAreas: ["Tecnologia", "Programação", "Desenvolvimento Web"],
    preferredCourseTypes: ["graduacao", "tecnico"],
    preferredFormat: ["hibrido", "online"],
    notes: "Interessada em cursos de tecnologia. Tem disponibilidade para aulas noturnas.",
    interestedCourses: [
      {
        courseId: "1",
        courseName: "Análise e Desenvolvimento de Sistemas",
        interestLevel: "alto",
      },
    ],
    financialInfo: {
      paymentPlan: "parcelado",
      scholarship: false,
      paymentStatus: "pendente",
    },
    totalValue: 0,
    createdAt: new Date("2023-12-01"),
  },
  {
    id: "2",
    name: "João Santos",
    email: "joao.santos@email.com",
    phone: "(21) 88888-8888",
    status: "matriculado",
    lastContact: new Date("2024-01-20"),
    nextContact: null,
    educationalBackground: "Graduação em Administração",
    interestAreas: ["Gestão", "Projetos", "Liderança"],
    preferredCourseTypes: ["pos", "especializacao"],
    preferredFormat: ["online"],
    notes: "Busca especialização para crescimento na carreira atual.",
    interestedCourses: [
      {
        courseId: "2",
        courseName: "MBA em Gestão de Projetos",
        interestLevel: "alto",
      },
    ],
    financialInfo: {
      paymentPlan: "parcelado",
      scholarship: false,
      paymentStatus: "parcial",
    },
    totalValue: 24000,
    createdAt: new Date("2023-10-15"),
  },
  {
    id: "3",
    name: "Ana Costa",
    email: "ana.costa@email.com",
    phone: "(31) 77777-7777",
    status: "contatado",
    lastContact: new Date("2024-01-10"),
    nextContact: new Date("2024-01-25"),
    educationalBackground: "Ensino Médio Completo",
    interestAreas: ["Saúde", "Enfermagem", "Cuidados"],
    preferredCourseTypes: ["tecnico"],
    preferredFormat: ["presencial"],
    notes: "Primeira formação na área de saúde. Muito motivada.",
    interestedCourses: [
      {
        courseId: "3",
        courseName: "Técnico em Enfermagem",
        interestLevel: "medio",
      },
    ],
    financialInfo: {
      paymentStatus: "pendente",
    },
    totalValue: 0,
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "4",
    name: "Carlos Oliveira",
    email: "carlos.oliveira@email.com",
    phone: "(41) 66666-6666",
    status: "prospecto",
    lastContact: new Date("2023-12-20"),
    nextContact: new Date("2024-01-30"),
    educationalBackground: "Graduação em Marketing",
    interestAreas: ["Marketing Digital", "Redes Sociais", "SEO"],
    preferredCourseTypes: ["especializacao", "profissionalizante"],
    preferredFormat: ["online", "hibrido"],
    notes: "Busca atualização na área de marketing digital.",
    interestedCourses: [
      {
        courseId: "4",
        courseName: "Especialização em Marketing Digital",
        interestLevel: "baixo",
      },
    ],
    financialInfo: {
      paymentStatus: "pendente",
    },
    totalValue: 0,
    createdAt: new Date("2023-11-01"),
  },
  {
    id: "5",
    name: "Fernanda Lima",
    email: "fernanda.lima@email.com",
    phone: "(51) 55555-5555",
    status: "desistente",
    lastContact: new Date("2023-11-15"),
    nextContact: null,
    educationalBackground: "Ensino Médio Completo",
    interestAreas: ["Administração", "Excel", "Office"],
    preferredCourseTypes: ["profissionalizante"],
    preferredFormat: ["online"],
    notes: "Desistiu por questões financeiras.",
    interestedCourses: [
      {
        courseId: "5",
        courseName: "Excel Avançado e VBA",
        interestLevel: "medio",
      },
    ],
    financialInfo: {
      paymentStatus: "pendente",
    },
    totalValue: 0,
    createdAt: new Date("2023-11-01"),
  },
]

export const mockActivities: Activity[] = [
  {
    id: "1",
    leadId: "1",
    leadName: "Maria Silva",
    type: "call",
    description: "Ligação para apresentar detalhes do curso de ADS",
    date: new Date("2024-01-15"),
  },
  {
    id: "2",
    leadId: "2",
    leadName: "João Santos",
    type: "enrollment",
    description: "Matrícula confirmada - MBA em Gestão de Projetos",
    date: new Date("2024-01-20"),
    value: 24000,
  },
  {
    id: "3",
    leadId: "3",
    leadName: "Ana Costa",
    type: "email",
    description: "Envio de material sobre o curso de Técnico em Enfermagem",
    date: new Date("2024-01-10"),
  },
  {
    id: "4",
    leadId: "1",
    leadName: "Maria Silva",
    type: "follow_up",
    description: "Follow-up sobre interesse no curso de ADS",
    date: new Date("2024-01-12"),
  },
]

export const mockAlerts: Alert[] = [
  {
    id: "1",
    type: "deadline",
    leadId: "1",
    leadName: "Maria Silva",
    message: "Prazo de inscrição para ADS termina em 5 dias",
    priority: "high",
    date: new Date("2024-01-25"),
  },
  {
    id: "2",
    type: "follow_up",
    leadId: "3",
    leadName: "Ana Costa",
    message: "Follow-up agendado para hoje",
    priority: "medium",
    date: new Date("2024-01-25"),
  },
  {
    id: "3",
    type: "new_lead",
    leadId: "4",
    leadName: "Carlos Oliveira",
    message: "Novo lead sem contato há mais de 30 dias",
    priority: "high",
    date: new Date("2024-01-24"),
  },
]

export const mockMatriculations: Matriculation[] = [
  {
    id: "1",
    studentId: "2",
    studentName: "João Santos",
    courseId: "2",
    courseName: "MBA em Gestão de Projetos",
    enrollmentDate: new Date("2024-01-20"),
    startDate: new Date("2024-04-10"),
    endDate: new Date("2025-10-10"),
    status: "ativa",
    paymentStatus: "parcial",
    financialGuarantor: {
      name: "Roberto Santos",
      relationship: "Pai",
      phone: "(21) 98765-4321",
      email: "roberto.santos@email.com",
    },
    grades: [
      {
        id: "1",
        matriculationId: "1",
        studentId: "2",
        studentName: "João Santos",
        courseId: "2",
        courseName: "MBA em Gestão de Projetos",
        subjectName: "Fundamentos de Gestão de Projetos",
        period: "2024.1",
        grade: 8.5,
        maxGrade: 10,
        status: "aprovado",
        date: new Date("2024-06-15"),
      },
      {
        id: "2",
        matriculationId: "1",
        studentId: "2",
        studentName: "João Santos",
        courseId: "2",
        courseName: "MBA em Gestão de Projetos",
        subjectName: "Metodologias Ágeis",
        period: "2024.1",
        grade: 7.8,
        maxGrade: 10,
        status: "aprovado",
        date: new Date("2024-06-30"),
      },
    ],
  },
  {
    id: "2",
    studentId: "6",
    studentName: "Pedro Almeida",
    courseId: "1",
    courseName: "Análise e Desenvolvimento de Sistemas",
    enrollmentDate: new Date("2023-12-15"),
    startDate: new Date("2024-03-01"),
    endDate: new Date("2026-09-01"),
    status: "ativa",
    paymentStatus: "completo",
    grades: [
      {
        id: "3",
        matriculationId: "2",
        studentId: "6",
        studentName: "Pedro Almeida",
        courseId: "1",
        courseName: "Análise e Desenvolvimento de Sistemas",
        subjectName: "Lógica de Programação",
        period: "2024.1",
        grade: 9.2,
        maxGrade: 10,
        status: "aprovado",
        date: new Date("2024-05-20"),
      },
    ],
  },
  {
    id: "3",
    studentId: "7",
    studentName: "Juliana Mendes",
    courseId: "3",
    courseName: "Técnico em Enfermagem",
    enrollmentDate: new Date("2024-01-10"),
    startDate: new Date("2024-02-15"),
    endDate: new Date("2026-02-15"),
    status: "ativa",
    paymentStatus: "bolsa",
    financialGuarantor: {
      name: "Marcos Mendes",
      relationship: "Irmão",
      phone: "(31) 98888-7777",
      email: "marcos.mendes@email.com",
    },
    grades: [],
  },
]

export const mockGrades: Grade[] = [
  {
    id: "1",
    matriculationId: "1",
    studentId: "2",
    studentName: "João Santos",
    courseId: "2",
    courseName: "MBA em Gestão de Projetos",
    subjectName: "Fundamentos de Gestão de Projetos",
    period: "2024.1",
    grade: 8.5,
    maxGrade: 10,
    status: "aprovado",
    date: new Date("2024-06-15"),
  },
  {
    id: "2",
    matriculationId: "1",
    studentId: "2",
    studentName: "João Santos",
    courseId: "2",
    courseName: "MBA em Gestão de Projetos",
    subjectName: "Metodologias Ágeis",
    period: "2024.1",
    grade: 7.8,
    maxGrade: 10,
    status: "aprovado",
    date: new Date("2024-06-30"),
  },
  {
    id: "3",
    matriculationId: "2",
    studentId: "6",
    studentName: "Pedro Almeida",
    courseId: "1",
    courseName: "Análise e Desenvolvimento de Sistemas",
    subjectName: "Lógica de Programação",
    period: "2024.1",
    grade: 9.2,
    maxGrade: 10,
    status: "aprovado",
    date: new Date("2024-05-20"),
  },
  {
    id: "4",
    matriculationId: "2",
    studentId: "6",
    studentName: "Pedro Almeida",
    courseId: "1",
    courseName: "Análise e Desenvolvimento de Sistemas",
    subjectName: "Banco de Dados",
    period: "2024.1",
    grade: 6.5,
    maxGrade: 10,
    status: "em_andamento",
    date: new Date("2024-06-10"),
  },
]

export const mockSettings: AppSettings = {
  theme: "light",
  language: "pt-BR",
  notifications: {
    email: true,
    push: true,
    sms: false,
  },
  defaultCurrency: "BRL",
  reportSettings: {
    defaultPeriod: "month",
    showInactiveStudents: false,
  },
}

export const monthlyRevenue = [
  { month: "Jul", value: 35000 },
  { month: "Ago", value: 42000 },
  { month: "Set", value: 38000 },
  { month: "Out", value: 51000 },
  { month: "Nov", value: 45000 },
  { month: "Dez", value: 57000 },
  { month: "Jan", value: 63000 },
]

export const salesFunnel = [
  { status: "Prospecto", count: 25, color: "#ef4444" },
  { status: "Contatado", count: 35, color: "#f59e0b" },
  { status: "Interessado", count: 28, color: "#3b82f6" },
  { status: "Inscrito", count: 15, color: "#8b5cf6" },
  { status: "Matriculado", count: 22, color: "#10b981" },
  { status: "Desistente", count: 8, color: "#6b7280" },
]

export const courseTypeDistribution = [
  { name: "Técnico", value: 15 },
  { name: "Graduação", value: 35 },
  { name: "Pós-graduação", value: 25 },
  { name: "Especialização", value: 18 },
  { name: "Profissionalizante", value: 12 },
]

export const courseFormatDistribution = [
  { name: "Presencial", value: 30 },
  { name: "Híbrido", value: 25 },
  { name: "Online", value: 45 },
]

export const gradeDistribution = [
  { range: "0-4", count: 5 },
  { range: "4-6", count: 12 },
  { range: "6-8", count: 28 },
  { range: "8-10", count: 18 },
]
